# Generated by Django 5.2.1 on 2025-05-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialty',
        ),
    ]
