# Generated by Django 5.1.2 on 2025-05-21 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_created_by_semanticlink_created_by_and_more'),
    ]

    operations = [
    ]
