# Generated by Django 5.1.2 on 2025-05-21 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_savedterm_indices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='savedterm',
            index=models.Index(fields=['user', 'term'], name='saved_term_user_term_idx'),
        ),
    ]
