# Generated by Django 5.1.2 on 2025-05-21 22:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_savedterm_saved_term_user_term_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedterm',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
