# Generated by Django 5.1.2 on 2025-05-22 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_savedterm_saved_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetworkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название модели ИИ (например, gpt-4o)', max_length=100)),
                ('version', models.CharField(blank=True, help_text='Версия модели ИИ', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Описание модели ИИ')),
                ('input_text', models.TextField(help_text='Входной текст запроса от пользователя')),
                ('output_text', models.TextField(help_text='Результат обработки нейросетью (например, список терминов)')),
                ('request_time', models.DateTimeField(auto_now_add=True, help_text='Дата и время запроса')),
                ('course', models.ForeignKey(blank=True, help_text='Курс, связанный с запросом (если применимо)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course')),
                ('discipline', models.ForeignKey(blank=True, help_text='Дисциплина, связанная с запросом (если применимо)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.discipline')),
                ('profile_type', models.ForeignKey(blank=True, help_text='Тип профиля пользователя (Студент/Преподаватель)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
                ('specialty', models.ForeignKey(blank=True, help_text='Специальность, связанная с запросом (если применимо)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.specialty')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, отправивший запрос', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
