# Generated by Django 5.1.2 on 2025-05-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_test_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanticlink',
            name='link_type',
            field=models.CharField(choices=[('related', 'Связан с'), ('example', 'Пример'), ('synonym', 'Синоним'), ('antonym', 'Антоним'), ('part_of', 'Часть'), ('uses', 'Использует'), ('cause', 'Причина'), ('effect', 'Следствие')], max_length=20),
        ),
    ]
