# Generated by Django 5.1.2 on 2025-05-25 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_semanticlink_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
