# Generated by Django 5.1.2 on 2025-05-26 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_course_profile_patronymic_profile_specialty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='savedterm',
            name='saved_term_user_term_idx',
        ),
        migrations.RemoveField(
            model_name='neuralnetworklog',
            name='course',
        ),
        migrations.RemoveField(
            model_name='neuralnetworklog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='neuralnetworklog',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='neuralnetworklog',
            name='profile_type',
        ),
        migrations.RemoveField(
            model_name='neuralnetworklog',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='neuralnetworklog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='neuralnetworklog',
            name='version',
        ),
        migrations.AlterUniqueTogether(
            name='semanticlink',
            unique_together={('source', 'target', 'link_type')},
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='created_by',
        ),
        migrations.AddField(
            model_name='neuralnetworklog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neuralnetworklog',
            name='response_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neuralnetworklog',
            name='successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='neuralnetworklog',
            name='input_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='neuralnetworklog',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='neuralnetworklog',
            name='output_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuralnetworklog',
            name='request_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='semanticlink',
            name='link_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='term',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course'),
        ),
        migrations.AlterField(
            model_name='term',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='term',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.discipline'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.specialty'),
        ),
        migrations.AlterUniqueTogether(
            name='savedterm',
            unique_together={('user', 'term')},
        ),
        migrations.AddField(
            model_name='viewedterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term'),
        ),
        migrations.AddField(
            model_name='viewedterm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='semanticlink',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='viewedterm',
            unique_together={('user', 'term')},
        ),
    ]
