# Generated by Django 5.1.2 on 2025-05-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_viewedterm_remove_savedterm_saved_term_user_term_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
